### ISSUE TITLE
Version 1.0.1 in PyPi

### ISSUE THREAD

**Issue by AusIV** [jezdez/django-staticfiles#16]
I noticed that with the release of django-staticfiles 1.1, older versions have been completely removed from PyPi. This is problematic, as version 1.1 is not compatible with Python 2.4.

I certainly understand dropping backwards compatibility with Python 2.4 in new versions, but at the very least older versions should remain available so that those of us who must use old versions of Python still have access to it. I've satisfied my dependencies by getting the source from github and building a package, but I imagine others will have this issue as well.

**Comment by jezdez** [comment]
Right, the default behaviour of PyPI is to hide the old releases from the public interface, even if they are actually still reachable if you know the url (e.g. http://pypi.python.org/pypi/django-staticfiles/1.0.1).

That said, I agree that I should un-hide the 1.0.X release on the landing page on PyPI to allow users of old versions of Python 2.4 to find it easily. The page (http://pypi.python.org/pypi/django-staticfiles/) should now list it, too.
