### ISSUE TITLE
Apps without models are ignored

### ISSUE THREAD

**Issue by vanschelven** [jezdez/django-staticfiles#2]
Django-staticfiles' codebase makes use of models.get_apps() in two locations. This method only returns those apps which have models (not just models.py, but one or more actual model definitions).

In some cases, I may want to override an app's media, without providing new models. 

I have provided two patches (sorry for bitbucket, google led me there first). I will not be offended if you find a more elegant solution (perhaps using an existing Django method?)

https://bitbucket.org/vanschelven/django-staticfiles/changeset/645a024c1760
https://bitbucket.org/vanschelven/django-staticfiles/changeset/bb5c7738d779

Klaas

**Comment by jezdez** [comment]
FYI, I've fixed this in Django trunk (http://code.djangoproject.com/changeset/15219) and will backport this soon here.

**Comment by jezdez** [comment]
Fixed in 85c5745ef1f54cb6d7df6e7e46980ed687376b76.
