### ISSUE TITLE
URL rewrite errors 

### ISSUE THREAD

**Issue by cyberdelia** [jezdez/django-staticfiles#20]
URL rewriting in css, fail on many common case use in css like ie hack like :

```
url(web-font.eot?#iefix)
```

And SVG id in url :

```
url(web-font.svg#webfontIyfZbseF)
```

And also try to rewrite data-uri :

```
url(data:font/woff;charset=utf-8;base64,d09GRgABAAAAADJoAA0AAAAAR2QAAQAAAAAAAAAAAAA)
```

And it's a common pratice used for cross-platform web-fonts support.

**Comment by jezdez** [comment]
This is basically a dupe of #18.
