### ISSUE TITLE
STATICFILES-EXCLUDED-APPS not defaulting to () as documented

### ISSUE THREAD

**Issue by eikeon** [jezdez/django-staticfiles#22]
I'm getting an AttributeError on line 123 of finders.py [1] since STATICFILES-EXCLUDED-APPS does not appear to be defaulting to () as documented here:

```
http://django-staticfiles.readthedocs.org/en/latest/settings/#staticfiles-excluded-apps
```

All works great if I add:

```
STATICFILES_EXCLUDED_APPS = ()
```

to my settings.

[1] https://github.com/jezdez/django-staticfiles/blob/develop/staticfiles/finders.py#L123

**Comment by jezdez** [comment]
Not sure what's causing this, but it works for me. All tests are passing, too: https://ci.enn.io/job/django-staticfiles/
