### ISSUE TITLE
Ordering of directories listed in STATICFILES_DIRS is not preserved

### ISSUE THREAD

**Issue by zbyte64** [jezdez/django-staticfiles#3]
When the directories are loaded into the FileSystemFinder object, it adds it to a set which does not preserve the order in which they are added. Consequently, when looking for files in the FileSystemFinder class, they are not necessarily looked up in the order specified in the settings file. If two directories listed in STATICFILES_DIRS contain the same file, it is not obvious to the programmer which will be chosen and there is no easy way for the programmer to specify (inherit filesystemfinder and overide in the settings seems to be the only way). I know that in the past this was not the case.

**Comment by jezdez** [comment]
Ah, good catch, indeed.

**Comment by jezdez** [comment]
Preserve order of STATICFILES_DIRS locations. Closed by 37d49961155a47c79075284bb2b53148b5df4d08. Thanks, zbyte64.
