### ISSUE TITLE
Enabling staticfiles prevents using --noreload option of runserver

### ISSUE THREAD

**Issue by rolo** [jezdez/django-staticfiles#6]
Hi there.

I've realised today that adding staticfiles to my installed apps prevents the --noreload switch from working on the manage.py runserver command (I use --noreload for my debugger).

It looks as though the runserver management replacement provided with staticfiles doesn't support this switch.  Is this a known trade off?

I've done a test with Django 1.3 using contrib.staticfiles and noreload works fine, so I guess I can just hang on for that if need be. :)

Thanks loads for a great app.

**Comment by jezdez** [comment]
That's a valid issue indeed, when I ported over the runserver command from Django back to django-staticfiles it must have slipped through the cracks. Thanks for reporting!

**Comment by jezdez** [comment]
Fixed!

**Comment by rolo** [comment]
Brilliant, thanks :)
